import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: './AtypTextTRIAL-Regular-BF65727125ea126.otf',
});

const inter = Roboto({
  subsets: ['cyrillic', 'greek', 'latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
